config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create]
          resources :likes, only: []
        end
      end
    end
  end

  post "/api/v1/auth/login", to: "authentication#login"
  post '/api/v1/user_post_comments', to: 'api/v1/comments#create'
  get 'api/v1/user_posts', to: "api/v1/posts#index"
  get 'api/v1/post_comments', to: "api/v1/comments#index"
  
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  require 'securerandom'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :comments
  has_many :posts, foreign_key: 'author_id'
  has_many :likes

  validates :name, presence: true
  validates :post_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def top_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/User/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_action :authenticate_request, only: [:create]
  skip_before_action :verify_authenticity_token, only: %i[login create]
  before_action :set_user, only: [:show]

  def index
    @users = User.all
    render json: @users, status: :ok
  end

  def show
    render json: @user, status: :ok
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render json: @user, status: :created
    else
      render json: { errors: @user.errors.full_messages },
             status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/views/users/index.html.erb
<section class="w-full">
  <div class="container">
    <div class="flex-row flex-wrap -m-2">
      <% @users.each do |user| %>
        <a href="<%= user_path(user) %>" class="p-2 lg:w-1/3 md:w-1/2 w-full">
          <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
            <img src=<%= user.photo%> alt="team" class="w-16 h-16 bg-gray-100 object-cover object-center flex-shrink-0 rounded-full mr-4" src="https://dummyimage.com/108x98">
            <div class="flex-grow">
              <h2 class="text-gray-900 title-font font-medium"><%= user.name %></h2>
              <p class="text-gray-500">number of posts: <%= user.posts.count%></p>
            </div>
          </div>
        </a>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="w-full">
  <div class="container w-full">
    <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg mb-4">
      <img src=<%= @user.photo%> alt="team" class="w-16 h-16 bg-gray-100 object-cover object-center flex-shrink-0 rounded-full mr-4" src="https://dummyimage.com/108x98">
      <div class="flex-grow">
        <h2 class="text-gray-900 title-font font-medium"><%= @user.name %></h2>
        <p class="text-gray-500">number of posts: <%= @user.posts.count%></p>
      </div>
    </div>
    <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg mb-4">
      <div class="flex-grow">
      <h2 class="text-gray-900 title-font font-medium">Bio: </h2>
        <p class="text-gray-500"><%= @user.bio%></p>
      </div>
    </div>
    <% @user.top_posts.each_with_index do |post, index| %>
        <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg mb-4">
          <div class="flex-grow"> 
            <a href="<%= user_post_path(@user, post) %>">
              <h2 class="text-gray-900 title-font font-medium" >Post #<%= index + 1 %></h2>
              <p class="text-gray-500"><%= post.text %></p>
            </a>
            <div class="flex space-x-2">
              <p class="text-gray-500">
                Comments: <%= post.comments.count %>, 
              </p>
              <p class="text-gray-500">
                Likes: <%= post.likes.count %>
              </p>
                <div>
                <%= form_with model: @new_like, url: user_post_likes_path(user_id: @user, post_id: post) do |f| %>
                  <div>
                    <%= button_tag( :class => "button_green") do %>
                    <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5 text-gray-500" viewBox="0 0 24 24">
                      <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                    </svg>
                    <% end %>
                  </div>
                <% end %>
                </div>
            </div>
          </div>
        </div>
      <div>
      <% if can? :destroy, post %>
          <%= button_to  'Delete',
              user_post_path(@user, post),
              method: :delete,
              class: "mb-20 text-white bg-indigo-500 border-0 py-2 w-full focus:outline-none hover:bg-indigo-600 rounded text-lg"
          %>
        <% end %>
      </div>
    <% end %>
  </div>
    <div class=" border-gray-200 border p-4 rounded-lg p-2 lg:w-1/3 md:w-1/2 w-full mx-auto">
      <div class="flex-grow">   
        <a href="<%= user_posts_path(@user) %>" class="flex justify-center">
          <button class="p-2 lg:w-1/3 md:w-1/2 w-full">
          See all posts
          </button>
        </a>
      </div>
    </div>
    <div class=" border-gray-200 border p-4 rounded-lg p-2 lg:w-1/3 md:w-1/2 w-full mx-auto">
      <div class="flex-grow">   
        <a href="<%= new_user_post_path(@user) %>" class="flex justify-center">
          <button class="p-2 lg:w-1/3 md:w-1/2 w-full">
          Make a Post
          </button>
        </a>
      </div>
    </div>
</section>