config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :new, :create]
          resources :likes, only: []
        end
      end
    end
  end

  post "/api/v1/auth/login", to: "authentication#login"
  post '/api/v1/user_post_comments', to: 'api/v1/comments#create'
  get 'api/v1/user_posts', to: "api/v1/posts#index"
  get 'api/v1/post_comments', to: "api/v1/comments#index"
  
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id', inverse_of: :posts
  has_many :comments
  has_many :likes

  after_save :update_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  self.per_page = 5

  def update_post_counter
    author.update(post_counter: author.posts.count)
  end

  def top_comments
    comments.order(created_at: :desc).limit(5)
  end

  def as_json(options = {})
    super({ except: %i[created_at updated_at] }.merge(options))
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  include JsonWebToken
  before_action :find_user
  def index
    @posts = @user.posts.includes(:comments, :likes)
    render json: @posts
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_user
  def index
    @posts = @user.posts.paginate(page: params[:page], per_page: 5).includes(:comments, :likes)
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render :json => @posts }
    # end
  end

  def show
    @post = Post.find(params[:id])
    @post_index = @post.author.posts.find_index { |post| post.id == @post.id }
  end

  def new
    @new_post = Post.new
  end

  def create
    @new_post = current_user.posts.build(post_params)
    if @new_post.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  def destroy
    @post = @user.posts.find(params[:id])
    @post.likes.destroy_all
    @post.comments.destroy_all
    if @post.destroy
      redirect_to user_posts_path(@user)
    else
      redirect_to user_post_path(@user)
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<section class="w-full">
  <div class="container w-full">
    <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg mb-4">
      <img src=<%= @user.photo%> alt="team" class="w-16 h-16 bg-gray-100 object-cover object-center flex-shrink-0 rounded-full mr-4" src="https://dummyimage.com/108x98">
      <div class="flex-grow">
        <h2 class="text-gray-900 title-font font-medium"><%= @user.name %></h2>
        <p class="text-gray-500">number of posts: <%= @user.posts.count%></p>
      </div>
    </div>
    <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg mb-4">
      <div class="flex-grow">
      <h2 class="text-gray-900 title-font font-medium">Bio: </h2>
        <p class="text-gray-500"><%= @user.bio%></p>
      </div>
    </div>
    <%= will_paginate @posts %>
    <% @posts.each_with_index do |post, index| %>
    <% post_index = (@posts.current_page - 1) * @posts.per_page + index + 1 %>
      <a href="<%= user_post_path(@user, post) %>" class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
        <div class="flex-grow"> 
          <h2 class="text-gray-900 title-font font-medium" >Post #<%= post_index %></h2>
          <h2 class="text-gray-900 title-font font-medium" ><%= post.title%></h2>
          <p class="text-gray-500"><%= post.text %></p>
          <p class="text-gray-500">Comments: <%= post.comments.size %> Likes: <%= post.likes.size %> </p>
        </div>
      </a>
      <div class="h-full border-gray-200 border p-4 rounded-lg">
        <% if post.comments.size >= 1 %> 
          <% post.top_comments.includes(:user).each do |comment| %>
            <div class="flex">
            <p class="mr-6 text-gray-500 py-1"><%= comment.user.name %>: <%= comment.text %></p>
            <% if can? :destroy, comment %>
              <%= button_to 'Delete',
                  user_post_comment_path(@user, post, comment),
                  method: :delete,
                  class: "text-white bg-indigo-500 border-0 py-1 pw-4 focus:outline-none hover:bg-indigo-600 rounded text-lg"
              %>
            <% end %>
            </div>
          <% end %>
          <% else %>
            <p class="text-gray-500">No comments yet.</p>
        <% end %>
      </div>
      <div>
      <% if can? :destroy, post %>
          <%= button_to  'Delete',
              user_post_path(@user, post),
              method: :delete,
              class: "mb-20 text-white bg-indigo-500 border-0 py-2 w-full focus:outline-none hover:bg-indigo-600 rounded text-lg"
          %>
        <% end %>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/new.html.erb
<section>
  <h1>New Post</h1>
  <%= form_with model: @new_post, url: user_posts_path(@user) do |f| %>
    <div>
      <%= f.label :title %><br>
      <%= f.text_field  :title %><br>
    </div>
    <div>
      <%= f.label :text %><br>
      <%= f.text_field :text %><br>
    </div>
    <div>
      <%= f.submit "post" %>
    </div>
  <% end %>
</section>

app/views/posts/show.html.erb
<% author = User.find(@post.author_id) %>

<section class="w-full">
  <div class="container w-full">
    <div class="h-full flex items-center border-gray-200 border p-4 rounded-lg">
      <div class="flex-grow">
        <h2 class="text-gray-900 title-font font-medium">Post #<%= @post_index + 1 %> by <%= author.name %> </h2>
        <h3 class="text-gray-900 title-font font-medium"><%= @post.title %> </h2>
        
        <div class="flex space-x-2">
          <p class="text-gray-500">
            Comments: <%= @post.comments.count %>, 
          </p>
          <p class="text-gray-500">
            Likes: <%= @post.likes.count %>
          </p>
            <div>
            <%= form_with model: @new_like, url: user_post_likes_path(user_id: @user, post_id: @post) do |f| %>
              <div>
                <%= button_tag( :class => "button_green") do %>
                <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5 text-gray-500" viewBox="0 0 24 24">
                  <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                </svg>
                <% end %>
              </div>
            <% end %>
            </div>
        </div>

        <p class="text-gray-500"><%= @post.text%></p>
      </div>
    </div>
    <div class="h-full border-gray-200 border p-4 rounded-lg mb-20">
      <% if @post.comments.size >= 1 %> 
        <% @post.comments.includes(:user).each do |comment| %>
          <div class="flex">
            <p class="mr-6 text-gray-500 py-1"><%= comment.user.name %>: <%= comment.text %></p>
            <% if can? :destroy, comment %>
              <%= button_to 'Delete',
                  user_post_comment_path(@user, @post, comment),
                  method: :delete,
                  class: "text-white bg-indigo-500 border-0 py-1 pw-4 focus:outline-none hover:bg-indigo-600 rounded text-lg"
              %>
            <% end %>
          </div>
        <% end %>
        <% else %>
          <p class="text-gray-500">No comments yet.</p>
      <% end %>
    </div>
    <div>
      <% if can? :destroy, @post %>
          <%= button_to  'Delete',
              user_post_path(@user, @post),
              method: :delete,
              class: "mb-20 text-white bg-indigo-500 border-0 py-2 w-full focus:outline-none hover:bg-indigo-600 rounded text-lg"
          %>
        <% end %>
    </div>
    <div class=" border-gray-200 border p-4 rounded-lg p-2 lg:w-1/3 md:w-1/2 w-full mx-auto">
      <div class="flex-grow">   
        <a href="<%= new_user_post_comment_path(@post.author, @post) %>" class="flex justify-center">
          <button class="p-2 lg:w-1/3 md:w-1/2 w-full">
          Make a Comment
          </button>
        </a>
      </div>
    </div>
  </div>
</section>